http.host: 0.0.0.0
## read password from logstash.keystore
# xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
# xpack.monitoring.elasticsearch.hosts: https://elasticsearch:9200
# xpack.monitoring.elasticsearch.username: logstash_system
# xpack.monitoring.elasticsearch.ssl.certificate_authority: /certs/ssl/ca/ca.crt

## set persistent queue
# queue.type: persisted
# path.queue: /queue
# queue.page_capacity: 64mb
# queue.drain: false
# queue.max_events: 0
# queue.max_bytes: 4gb